### ISSUE TITLE
Parallel and Segmented Downloads No Longer Working

### ISSUE THREAD

**Issue by copaceticgeek** [userdocs/lftp-windows#15] opened 2020-12-13 03:21 UTC
I recently updated to the newest build. Since then parallel and segmented downloads are no longer working. When using pget-to-local the terminal screen shows the following: 
![LFTP4WIN01](https://user-images.githubusercontent.com/5106442/102002226-2e613d00-3caf-11eb-856d-4d0a82abba46.png)
It appears that it only uses one connection now.

**Comment by userdocs** [comment] 2020-12-13 11:59
It has always been like this for `pget-to-local`.

1 file is transferred using n amount of parts. There are no parallel transfers with a pget transfer. Only a mirror transfer has parallel and pget.

This can also be demonstrated by opening the `.lftp.lftp-pget-status` to see the number of parts defined.

For example, when using the defaults.

```
size=5368709120
0.pos=62750720
0.limit=1073741824
1.pos=1096941568
1.limit=2147483648
2.pos=2173730816
2.limit=3221225472
3.pos=3251339264
3.limit=4294967296
4.pos=4324589568
4.limit=5368709120
```

I am not sure what the problem is here since what you are claiming is a bug, is actually how it has always behaved for this particular custom command.

**Comment by userdocs** [comment] 2020-12-13 12:07
Please look here https://lftp.yar.ru/lftp-man.html

Search for `-P` (case sensitive) or `--parallel` and you will see this is not a option for the pget command.

Please also check your task manager when using the pget command to see there will a number of ssh/cygwin task equal to the number of parts selected.

**Comment by copaceticgeek** [comment] 2020-12-13 23:09
Sorry for the confusion and lack of detail in my post. When using the pget command, it is no longer breaking the download into segments. In task manager there is only one instance of ssh/cygwin running. It is also no longer showing the status of the download with the "dots" and "circles" like before either.

When using the mirror command, it is no longer running parallel downloads or segmenting the files.

**Comment by userdocs** [comment] 2020-12-13 23:12
Try setting the override settings again. I have tested it and cant find any issues.

**Comment by copaceticgeek** [comment] 2020-12-13 23:27
Thank you. That worked. It is now behaving normally again.

**Comment by userdocs** [comment] 2020-12-13 23:28
actually, I think I see the problem. i'll fix it now

**Comment by userdocs** [comment] 2020-12-13 23:43
Ok, so there was a silly bug created by myself. I didn't notice it because of the override worked.

The check to decide if we should use the lftp conf was checking against the wrong filename. That is fixed now so it should work as expected with this fix https://github.com/userdocs/LFTP4WIN-CORE/commit/c593c182162f825f329bdf7b04f9b96f0436c03c

Thanks for letting me know.

**Closed as completed by userdocs** 2020-12-13 23:43 UTC
